name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"
          channel: "stable"

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run unit/widget tests
        run: flutter test --no-pub

      - name: Install iOS pods
        working-directory: ios
        run: pod install --repo-update

      - name: Build iOS (no codesign)
        run: flutter build ios --no-codesign
